import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-sans bg-gray-200"}>
        <div className=" text-center backdrop-blur justify-center h-16 flex items-center text-lg font-bold gap-10">
          <Link href="/" className="">
            home
          </Link>
          <Link href="/" className="">
            home
          </Link>
        </div>
        <div className="flex flex-col justify-center items-center">
          <div className="  w-screen sm:w-[640px] md:w-[700px] lg:w-[900px] pt-10 px-10 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
